"""Add deleted_at to InvoiceLine, InvoiceTaxBracket, and ProductCostHistory

Revision ID: 1b20cfbc47b7
Revises: 61ec016f182e
Create Date: 2026-07-09 15:35:14.414550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b20cfbc47b7'
down_revision: Union[str, Sequence[str], None] = '61ec016f182e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_lines', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('invoicetaxbracket', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('productcosthistory', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productcosthistory', 'deleted_at')
    op.drop_column('invoicetaxbracket', 'deleted_at')
    op.drop_column('invoice_lines', 'deleted_at')
    # ### end Alembic commands ###
