"""init

Revision ID: 1db3dc470884
Revises: 
Create Date: 2026-06-29 10:45:48.870713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db3dc470884'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('contactInfo', sa.String(length=255), nullable=True),
    sa.Column('vatID', sa.String(length=50), nullable=True),
    sa.Column('legalName', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contacts', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_vatID'), 'suppliers', ['vatID'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serialNumber', sa.String(length=100), nullable=True),
    sa.Column('supplierId', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('dueDate', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxableAdditionalCost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('netAdditionalCost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payeAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('greenPointAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ibeeAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('ocrStatus', sa.String(length=50), nullable=True),
    sa.Column('paidStatus', sa.String(length=50), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('isRefund', sa.Boolean(), nullable=True),
    sa.Column('isReconciled', sa.Boolean(), nullable=True),
    sa.Column('isRecurrent', sa.Boolean(), nullable=True),
    sa.Column('documentInboxEmail', sa.String(length=255), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('fileUrl', sa.String(length=1000), nullable=True),
    sa.Column('uploaderId', sa.String(length=100), nullable=True),
    sa.Column('propertyId', sa.String(length=100), nullable=True),
    sa.Column('categoryId', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['supplierId'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_serialNumber'), 'invoices', ['serialNumber'], unique=True)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoiceId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unitPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('totalPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('providerCode', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('grossPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discountPct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('appliedDiscount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('otherFees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nominalPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operational_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('invoiceId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_brackets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoiceId', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxRate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('equivalenceSurchargeRate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('equivalenceSurcharge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_brackets')
    op.drop_table('operational_incidents')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_invoices_serialNumber'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_suppliers_vatID'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
