"""Add ondelete SET NULL to referenced_items.invoice_line_id

Revision ID: 2103e0646ca2
Revises: 475e3adcfffc
Create Date: 2026-07-07 15:53:06.985787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2103e0646ca2'
down_revision: Union[str, Sequence[str], None] = '475e3adcfffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('referenced_items_invoice_line_id_fkey', 'referenced_items', type_='foreignkey')
    op.create_foreign_key(None, 'referenced_items', 'invoice_lines', ['invoice_line_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referenced_items', type_='foreignkey')
    op.create_foreign_key('referenced_items_invoice_line_id_fkey', 'referenced_items', 'invoice_lines', ['invoice_line_id'], ['id'])
    # ### end Alembic commands ###
