"""add_ocr_llm_durations

Revision ID: 311a353bda6f
Revises: 63de3e9c6fc7
Create Date: 2026-06-30 09:56:04.497673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '311a353bda6f'
down_revision: Union[str, Sequence[str], None] = '63de3e9c6fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('ocr_duration', sa.Float(), nullable=True))
    op.add_column('invoice', sa.Column('llm_duration', sa.Float(), nullable=True))
    op.alter_column('suppliedproduct', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('supplier', 'address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('supplier', 'contacts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier', 'contacts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('supplier', 'address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('suppliedproduct', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('invoice', 'llm_duration')
    op.drop_column('invoice', 'ocr_duration')
    # ### end Alembic commands ###
