"""add_ocr_llm_durations

Revision ID: 311a353bda6f
Revises: 71c87a58b212
Create Date: 2026-06-30 09:56:04.497673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '311a353bda6f'
down_revision: Union[str, Sequence[str], None] = '71c87a58b212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('ocr_duration', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('llm_duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'llm_duration')
    op.drop_column('invoices', 'ocr_duration')
    # ### end Alembic commands ###
