"""Add Supplier fields and SupplierContact

Revision ID: 3d4d4a7ae06e
Revises: c964c0773328
Create Date: 2026-07-02 12:03:11.804161

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d4d4a7ae06e'
down_revision: Union[str, Sequence[str], None] = 'c964c0773328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('suppliers', sa.Column('accounting_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('suppliers', sa.Column('sanitary_registration', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('suppliers', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('suppliers', sa.Column('payment_info', sa.JSON(), nullable=True))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('suppliers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_suppliers_category_id'), 'suppliers', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_category_id'), table_name='suppliers')
    op.drop_column('suppliers', 'deleted_at')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'payment_info')
    op.drop_column('suppliers', 'tags')
    op.drop_column('suppliers', 'sanitary_registration')
    op.drop_column('suppliers', 'accounting_account')
    op.drop_column('suppliers', 'category_id')
    # ### end Alembic commands ###
