"""add_recipetag_table

Revision ID: 475e3adcfffc
Revises: 55bf151278d4
Create Date: 2026-07-06 23:18:39.775270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '475e3adcfffc'
down_revision: Union[str, Sequence[str], None] = '55bf151278d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipetag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_preparation', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipetag_tag_id'), 'recipetag', ['tag_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipetag_tag_id'), table_name='recipetag')
    op.drop_table('recipetag')
    # ### end Alembic commands ###
