"""add categories table

Revision ID: 4a03a0b80781
Revises: 2103e0646ca2
Create Date: 2026-07-07 17:34:04.094038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a03a0b80781'
down_revision: Union[str, Sequence[str], None] = '2103e0646ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operational_incidents')
    op.drop_index('ix_categories_category_id', table_name='categories')
    op.create_unique_constraint(None, 'categories', ['category_id'])
    op.create_foreign_key(None, 'restaurant', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index('ix_categories_category_id', 'categories', ['category_id'], unique=True)
    op.create_table('operational_incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('invoiceId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['invoices.id'], name='operational_incidents_invoiceId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='operational_incidents_pkey')
    )
    # ### end Alembic commands ###
