"""add_image_url_to_recipe

Revision ID: 55bf151278d4
Revises: e5e01ab1d0ae
Create Date: 2026-07-06 23:04:03.977141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '55bf151278d4'
down_revision: Union[str, Sequence[str], None] = 'e5e01ab1d0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image_url')
    # ### end Alembic commands ###
