"""Add deleted_at to SupplierContact, SuppliedProduct, and Invoice

Revision ID: 61ec016f182e
Revises: 9713a67edc4f
Create Date: 2026-07-09 15:25:38.913834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61ec016f182e'
down_revision: Union[str, Sequence[str], None] = '9713a67edc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('suppliedproduct', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('supplier_contacts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_contacts', 'deleted_at')
    op.drop_column('suppliedproduct', 'deleted_at')
    op.drop_column('invoices', 'deleted_at')
    # ### end Alembic commands ###
