a"""Add supplier_code to supplier

Revision ID: 660aedb5d1ed
Revises: aedc585cd3b8
Create Date: 2026-07-02 16:19:45.955740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '660aedb5d1ed'
down_revision: Union[str, Sequence[str], None] = 'aedc585cd3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('supplier_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.drop_column('suppliers', 'supplier_code')
    # ### end Alembic commands ###
