"""Add deleted_at and merged_into_id to products

Revision ID: 80cb315cb9a4
Revises: 7fa2bc0e6642
Create Date: 2026-07-10 12:03:18.712447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80cb315cb9a4'
down_revision: Union[str, Sequence[str], None] = '7fa2bc0e6642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_permissions_module', table_name='role_permissions')
    op.drop_index('ix_role_permissions_restaurant_id', table_name='role_permissions')
    op.drop_index('ix_role_permissions_role_name', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.create_index(op.f('ix_app_role_permissions_module'), 'app_role_permissions', ['module'], unique=False)
    op.create_index(op.f('ix_app_role_permissions_restaurant_id'), 'app_role_permissions', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_app_role_permissions_role_name'), 'app_role_permissions', ['role_name'], unique=False)
    op.create_unique_constraint('uq_role_permission_module', 'app_role_permissions', ['restaurant_id', 'role_name', 'module'])
    op.create_unique_constraint(None, 'categories', ['category_id'])
    op.create_foreign_key(None, 'categories', 'categories', ['parent_category_id'], ['category_id'])
    op.alter_column('inventories', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_inventories_name', table_name='inventories')
    op.drop_index('ix_inventories_status', table_name='inventories')
    op.drop_column('inventories', 'inventory_date')
    op.drop_column('inventories', 'notes')
    op.drop_column('inventories', 'created_by')
    op.add_column('products', sa.Column('merged_into_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_products_merged_into_id'), 'products', ['merged_into_id'], unique=False)
    op.create_foreign_key(None, 'products', 'categories', ['app_category_id'], ['category_id'])
    op.create_foreign_key(None, 'suppliers', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_merged_into_id'), table_name='products')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'merged_into_id')
    op.add_column('inventories', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('inventories', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('inventories', sa.Column('inventory_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_inventories_status', 'inventories', ['status'], unique=False)
    op.create_index('ix_inventories_name', 'inventories', ['name'], unique=False)
    op.alter_column('inventories', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint('uq_role_permission_module', 'app_role_permissions', type_='unique')
    op.drop_index(op.f('ix_app_role_permissions_role_name'), table_name='app_role_permissions')
    op.drop_index(op.f('ix_app_role_permissions_restaurant_id'), table_name='app_role_permissions')
    op.drop_index(op.f('ix_app_role_permissions_module'), table_name='app_role_permissions')
    op.create_table('role_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('view', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('create', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('edit', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('export', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name='role_permissions_restaurant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='role_permissions_pkey'),
    sa.UniqueConstraint('restaurant_id', 'role_name', 'module', name='uq_role_permission_module', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_role_permissions_role_name', 'role_permissions', ['role_name'], unique=False)
    op.create_index('ix_role_permissions_restaurant_id', 'role_permissions', ['restaurant_id'], unique=False)
    op.create_index('ix_role_permissions_module', 'role_permissions', ['module'], unique=False)
    # ### end Alembic commands ###
