"""change parent_category_id to string

Revision ID: 81e23555dafb
Revises: cedb270dc524
Create Date: 2026-07-03 13:12:44.418087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81e23555dafb'
down_revision: Union[str, Sequence[str], None] = 'cedb270dc524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop the old foreign key constraint
    op.drop_constraint('categories_parent_category_id_fkey', 'categories', type_='foreignkey')
    
    # 2. Add temporary column
    op.add_column('categories', sa.Column('new_parent_category_id', sa.String(), nullable=True))
    
    # 3. Update temporary column with mapped data
    op.execute(
        "UPDATE categories SET new_parent_category_id = c2.category_id "
        "FROM categories c2 WHERE c2.id = categories.parent_category_id::int"
    )
    
    # 4. Drop old column and rename new column
    op.drop_column('categories', 'parent_category_id')
    op.alter_column('categories', 'new_parent_category_id', new_column_name='parent_category_id')
    
    # 5. Add the new foreign key
    op.create_foreign_key(None, 'categories', 'categories', ['parent_category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_parent_category_id_fkey', 'categories', 'categories', ['parent_category_id'], ['id'])
    op.alter_column('categories', 'parent_category_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
