"""add_products_inventory_schema

Revision ID: 8f62db44eab7
Revises: 83ec85f68bdf
Create Date: 2026-07-03 12:39:51.365685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f62db44eab7'
down_revision: Union[str, Sequence[str], None] = 'cf5a7867c65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=False)
    op.create_index(op.f('ix_expense_categories_parent_id'), 'expense_categories', ['parent_id'], unique=False)
    op.create_table('inventories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inventory_date', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventories_name'), 'inventories', ['name'], unique=False)
    op.create_index(op.f('ix_inventories_status'), 'inventories', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price_difference_percentage', sa.Float(), nullable=True),
    sa.Column('unit_of_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit_of_measure_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('bookmarked', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('merged', sa.Boolean(), nullable=False),
    sa.Column('imported', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('product_suppliers',
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('haddock_supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'supplier_id')
    )
    op.create_index(op.f('ix_product_suppliers_haddock_supplier_id'), 'product_suppliers', ['haddock_supplier_id'], unique=False)
    op.create_table('referenced_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expense_item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_line_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referenced_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dish_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('base_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_unit_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('warehouse_quantity', sa.Float(), nullable=False),
    sa.Column('purchase_quantity', sa.Float(), nullable=False),
    sa.Column('purchase_unit_of_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_accumulated', sa.Float(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('haddock_supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['referenced_item_id'], ['referenced_items.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_dish_id'), 'inventory_items', ['dish_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_inventory_id'), 'inventory_items', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_kind'), 'inventory_items', ['kind'], unique=False)
    op.create_index(op.f('ix_inventory_items_product_id'), 'inventory_items', ['product_id'], unique=False)
    op.create_table('product_formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('base_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_unit_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_per_base_unit', sa.Float(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('haddock_referenced_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['haddock_referenced_id'], ['referenced_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_formats_product_id'), 'product_formats', ['product_id'], unique=False)
    op.create_table('product_references',
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referenced_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referenced_item_id'], ['referenced_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'referenced_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_references')
    op.drop_index(op.f('ix_product_formats_product_id'), table_name='product_formats')
    op.drop_table('product_formats')
    op.drop_index(op.f('ix_inventory_items_product_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_kind'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_inventory_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_dish_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_table('referenced_items')
    op.drop_index(op.f('ix_product_suppliers_haddock_supplier_id'), table_name='product_suppliers')
    op.drop_table('product_suppliers')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_inventories_status'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_name'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_expense_categories_parent_id'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_name'), table_name='expense_categories')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
