"""Add restaurant_id to products and inventories

Revision ID: 9713a67edc4f
Revises: bd32afdeeb1a
Create Date: 2026-07-08 13:09:22.519994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9713a67edc4f'
down_revision: Union[str, Sequence[str], None] = 'bd32afdeeb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventories_restaurant_id'), 'inventories', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'inventories', 'restaurant', ['restaurant_id'], ['id'])
    
    op.add_column('products', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_restaurant_id'), 'products', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'products', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_restaurant_id'), table_name='products')
    op.drop_column('products', 'restaurant_id')
    
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.drop_index(op.f('ix_inventories_restaurant_id'), table_name='inventories')
    op.drop_column('inventories', 'restaurant_id')
    # ### end Alembic commands ###
