"""Add owner_id to restaurant

Revision ID: 9767ada7a2f2
Revises: 99003a8cc82d
Create Date: 2026-07-02 18:32:06.896939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9767ada7a2f2'
down_revision: Union[str, Sequence[str], None] = '99003a8cc82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_duplicate', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('invoices', sa.Column('llm_confidence', sa.Float(), nullable=True))
    op.add_column('restaurant', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'restaurant', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_column('restaurant', 'owner_id')
    op.drop_column('invoices', 'llm_confidence')
    op.drop_column('invoices', 'is_duplicate')
    # ### end Alembic commands ###
