"""remove_product_references_and_referenced_items

Revision ID: 98341f812d41
Revises: eb5b80feef3e
Create Date: 2026-07-09 12:07:18.403880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98341f812d41'
down_revision: Union[str, Sequence[str], None] = 'eb5b80feef3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Remove product_references and referenced_items tables.
    These are replaced by the alias-based lookup pattern via product_aliases.
    """
    # Drop FK constraints and dependent columns FIRST, then drop the tables
    op.drop_constraint('inventory_items_referenced_item_id_fkey', 'inventory_items', type_='foreignkey')
    op.drop_column('inventory_items', 'referenced_item_id')
    op.drop_constraint('product_formats_haddock_referenced_id_fkey', 'product_formats', type_='foreignkey')
    op.drop_column('product_formats', 'haddock_referenced_id')
    # Now safe to drop the tables (product_references must go before referenced_items)
    op.drop_table('product_references')
    op.drop_table('referenced_items')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_formats', sa.Column('haddock_referenced_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_formats_haddock_referenced_id_fkey', 'product_formats', 'referenced_items', ['haddock_referenced_id'], ['id'])
    op.add_column('inventory_items', sa.Column('referenced_item_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('inventory_items_referenced_item_id_fkey', 'inventory_items', 'referenced_items', ['referenced_item_id'], ['id'])
    op.add_column('inventories', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('inventories', sa.Column('inventory_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('inventories', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_inventories_status', 'inventories', ['status'], unique=False)
    op.create_index('ix_inventories_name', 'inventories', ['name'], unique=False)
    op.alter_column('inventories', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index('ix_categories_category_id', 'categories', ['category_id'], unique=True)
    op.create_table('product_references',
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('referenced_item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_references_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referenced_item_id'], ['referenced_items.id'], name='product_references_referenced_item_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'referenced_item_id', name='product_references_pkey')
    )
    op.create_table('referenced_items',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expense_item_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('supplier_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invoice_line_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], name='referenced_items_invoice_line_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='referenced_items_pkey')
    )
    # ### end Alembic commands ###
