"""extend_recipes_schema

Revision ID: a898ea8dbcfc
Revises: b6da10406dbf
Create Date: 2026-07-06 16:28:28.437530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a898ea8dbcfc'
down_revision: Union[str, Sequence[str], None] = 'b6da10406dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('dish_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recipe', sa.Column('is_preparation', sa.Boolean(), nullable=False))
    op.add_column('recipe', sa.Column('unit_of_measure', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('recipe', sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recipe', sa.Column('tag_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recipe', sa.Column('base_price', sa.Float(), nullable=False))
    op.add_column('recipe', sa.Column('tax_amount', sa.Float(), nullable=False))
    op.create_index(op.f('ix_recipe_dish_id'), 'recipe', ['dish_id'], unique=True)
    op.create_index(op.f('ix_recipe_is_preparation'), 'recipe', ['is_preparation'], unique=False)
    op.add_column('recipeingredient', sa.Column('child_recipe_id', sa.Integer(), nullable=True))
    op.alter_column('recipeingredient', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'recipeingredient', 'recipe', ['child_recipe_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_suppliers_category_id'), 'suppliers', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_category_id'), table_name='suppliers')
    op.drop_constraint(None, 'recipeingredient', type_='foreignkey')
    op.alter_column('recipeingredient', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recipeingredient', 'child_recipe_id')
    op.drop_index(op.f('ix_recipe_is_preparation'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_dish_id'), table_name='recipe')
    op.drop_column('recipe', 'tax_amount')
    op.drop_column('recipe', 'base_price')
    op.drop_column('recipe', 'tag_name')
    op.drop_column('recipe', 'tag_id')
    op.drop_column('recipe', 'unit_of_measure')
    op.drop_column('recipe', 'is_preparation')
    op.drop_column('recipe', 'dish_id')
    # ### end Alembic commands ###
