"""Add notes to supplier

Revision ID: aedc585cd3b8
Revises: 47ea4eeb30c3
Create Date: 2026-07-02 14:28:14.965920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aedc585cd3b8'
down_revision: Union[str, Sequence[str], None] = '47ea4eeb30c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operational_incidents')
    op.drop_table('tax_brackets')
    op.drop_column('invoices', 'property_id')
    op.drop_column('invoices', 'document_inbox_email')
    op.drop_column('invoices', 'observations')
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'taxable_additional_cost')
    op.drop_column('invoices', 'net_additional_cost')
    op.add_column('suppliers', sa.Column('notes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'notes')
    op.add_column('invoices', sa.Column('net_additional_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('taxable_additional_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('observations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('document_inbox_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('property_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('tax_brackets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoiceId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('taxRate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('tax', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('equivalenceSurchargeRate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('equivalenceSurcharge', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['invoices.id'], name='tax_brackets_invoiceId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tax_brackets_pkey')
    )
    op.create_table('operational_incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('invoiceId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['invoices.id'], name='operational_incidents_invoiceId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='operational_incidents_pkey')
    )
    # ### end Alembic commands ###
