"""add status and suggested_master_product_id to products

Revision ID: bc39ab922893
Revises: 80cb315cb9a4
Create Date: 2026-07-10 13:06:15.052323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bc39ab922893'
down_revision: Union[str, Sequence[str], None] = '80cb315cb9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('master_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['master_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_aliases_alias_name'), 'product_aliases', ['alias_name'], unique=False)
    op.create_index(op.f('ix_product_aliases_master_product_id'), 'product_aliases', ['master_product_id'], unique=False)
    op.drop_table('operational_incidents')
    op.add_column('products', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default='ACTIVE', nullable=False))
    op.add_column('products', sa.Column('suggested_master_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_products_suggested_master_product_id'), 'products', ['suggested_master_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_suggested_master_product_id'), table_name='products')
    op.drop_column('products', 'suggested_master_product_id')
    op.drop_column('products', 'status')
    op.create_table('operational_incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('invoiceId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['invoices.id'], name='operational_incidents_invoiceId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='operational_incidents_pkey')
    )
    op.drop_index(op.f('ix_product_aliases_master_product_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_alias_name'), table_name='product_aliases')
    op.drop_table('product_aliases')
    # ### end Alembic commands ###
