"""add_gra_um_to_invoiceline

Revision ID: c964c0773328
Revises: 311a353bda6f
Create Date: 2026-06-30 10:06:02.197379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c964c0773328'
down_revision: Union[str, Sequence[str], None] = '311a353bda6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_lines', sa.Column('gra', sa.Float(), nullable=True))
    op.add_column('invoice_lines', sa.Column('u_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_lines', 'u_m')
    op.drop_column('invoice_lines', 'gra')
    # ### end Alembic commands ###
