"""change supplier category_id to string

Revision ID: cf5a7867c65e
Revises: 81e23555dafb
Create Date: 2026-07-03 14:47:49.806353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf5a7867c65e'
down_revision: Union[str, Sequence[str], None] = '81e23555dafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Drop old constraint
    op.drop_constraint('suppliers_category_id_fkey', 'suppliers', type_='foreignkey')
    
    # 2. Add temporary column
    op.add_column('suppliers', sa.Column('new_category_id', sa.String(), nullable=True))
    
    # 3. Map integer id to string category_id
    op.execute(
        "UPDATE suppliers SET new_category_id = c.category_id "
        "FROM categories c WHERE c.id = suppliers.category_id::int"
    )
    
    # 4. Drop old column and rename new one
    op.drop_column('suppliers', 'category_id')
    op.alter_column('suppliers', 'new_category_id', new_column_name='category_id')
    
    # 5. Add new constraint
    op.create_foreign_key(None, 'suppliers', 'categories', ['category_id'], ['category_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.create_foreign_key('suppliers_category_id_fkey', 'suppliers', 'categories', ['category_id'], ['id'])
    op.alter_column('suppliers', 'category_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
