"""add_notes_to_recipe

Revision ID: e5e01ab1d0ae
Revises: a898ea8dbcfc
Create Date: 2026-07-06 22:28:31.487444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e5e01ab1d0ae'
down_revision: Union[str, Sequence[str], None] = 'a898ea8dbcfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'notes')
    # ### end Alembic commands ###
