"""Add suggested match fields to InvoiceLine

Revision ID: eb5b80feef3e
Revises: 2103e0646ca2
Create Date: 2026-07-08 13:34:57.440671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb5b80feef3e'
down_revision: Union[str, Sequence[str], None] = '2103e0646ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_lines', sa.Column('suggested_product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoice_lines', sa.Column('suggested_confidence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_lines', 'suggested_confidence')
    op.drop_column('invoice_lines', 'suggested_product_id')
    # ### end Alembic commands ###
