"""add_status_and_suggested_master_product_id_to_products

Revision ID: ec8bc85caf10
Revises: b6da10406dbf
Create Date: 2026-07-07 11:20:41.171190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8bc85caf10'
down_revision: Union[str, Sequence[str], None] = 'b6da10406dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_category_id', table_name='categories')
    op.create_unique_constraint(None, 'categories', ['category_id'])
    op.drop_constraint('referenced_items_invoice_line_id_fkey', 'referenced_items', type_='foreignkey')
    op.create_foreign_key(None, 'referenced_items', 'invoice_lines', ['invoice_line_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_suppliers_category_id'), 'suppliers', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_category_id'), table_name='suppliers')
    op.drop_constraint(None, 'referenced_items', type_='foreignkey')
    op.create_foreign_key('referenced_items_invoice_line_id_fkey', 'referenced_items', 'invoice_lines', ['invoice_line_id'], ['id'])
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index('ix_categories_category_id', 'categories', ['category_id'], unique=True)
    # ### end Alembic commands ###
