# Global application constants

PRICE_SPIKE_THRESHOLD = 5.0
PRICE_SPIKE_HIGH_THRESHOLD = 15.0

TARGET_LABOR_PERCENTAGE = 30.0
UNDERSTAFFING_LABOR_PERCENTAGE = 15.0

QDRANT_COLLECTION_NAME = "hospitality_embeddings"
EMBEDDING_MODEL_NAME = "text-embedding-004"
GEMINI_MODEL_NAME = "gemini-2.0-flash"
