import { StyleSheet } from 'react-native';

export const sharedStyles = StyleSheet.create({
  card: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e1dd',
    padding: 16,
    borderRadius: 12,
    shadowColor: '#151515',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#151515',
    marginBottom: 8,
    fontFamily: 'Sora',
  },
  statCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e1dd',
    padding: 12,
    borderRadius: 10,
    width: '48%',
    marginBottom: 12,
    gap: 4,
    shadowColor: '#151515',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  statLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#8c8c89',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Sora',
  },
  statValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#151515',
    fontFamily: 'DM Mono',
  },
  statDiff: {
    fontSize: 9,
    fontWeight: '600',
    fontFamily: 'Sora',
  },
  sectionHeader: {
    fontSize: 14,
    fontWeight: '700',
    color: '#151515',
    marginBottom: 8,
    fontFamily: 'Sora',
  },
  screenTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#151515',
    fontFamily: 'Sora',
  },
  searchInput: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e1dd',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 12,
    color: '#151515',
    fontFamily: 'Sora',
  },
  primaryBtn: {
    backgroundColor: '#151515',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 11,
    fontFamily: 'Sora',
  },
  secondaryBtn: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e1dd',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryBtnText: {
    color: '#151515',
    fontWeight: '600',
    fontSize: 11,
    fontFamily: 'Sora',
  },
  errorBadge: {
    backgroundColor: '#fceaea',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  errorBadgeText: {
    color: '#b23a3a',
    fontSize: 8,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
});
